apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: test
servers: 1
agents: 2
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6443"
image: rancher/k3s:latest
volumes:
  - volume: /my/path:/some/path
    nodeFilters:
      - all
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 0.0.0.0:443:443
    nodeFilters:
      - loadbalancer
env:
  - envVar: bar=baz
    nodeFilters:
      - all
files:
  - description: 'Source: Embedded, Destination: Absolute path'
    source: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: foo
    destination: /var/lib/rancher/k3s/server/manifests/foo.yaml
  - description: 'Source: Embedded, Destination: Magic shortcut path'
    source: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: bar
    destination: k3s-manifests/bar.yaml # Resolved to /var/lib/rancher/k3s/server/manifests/bar.yaml
  - description: 'Source: Relative, Destination: Magic shortcut path'
    source: ns-baz.yaml
    destination: k3s-manifests-custom/baz.yaml # Resolved to /var/lib/rancher/k3s/server/manifests/custom/baz.yaml
  - description: 'Source: Relative, Destination: Magic shortcut path, Node: Servers only'
    source: ns-baz.yaml
    destination: k3s-manifests/baz.yaml # Resolved to /var/lib/rancher/k3s/server/manifests/baz.yaml
    nodeFilters:
    - "server:*"

options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
    disableImageVolume: false
  k3s:
    extraArgs:
      - arg: --tls-san=127.0.0.1
        nodeFilters:
          - server:*
    nodeLabels:
      - label: foo=bar
        nodeFilters:
          - server:0
          - loadbalancer
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    labels:
      - label: foo=bar
        nodeFilters:
          - server:0
          - loadbalancer
    ulimits:
      - name: nofile
        soft: 1024
        hard: 1024
