---
kind: pipeline
type: docker
name: main

platform:
  os: linux
  arch: amd64

steps:

  - name: k3d_lint
    image: golang:1.14
    commands:
      - make ci-setup
      - make check-fmt lint
    when:
      event:
        - push
        - pull_request
        - tag

  - name: k3d_tests
    image: docker:19.03
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - apk add git bash curl sudo jq make
      - sleep 5 # give docker enough time to start
      - make e2e
    when:
      event:
        - push
        - pull_request
        - tag

  - name: k3d_build
    image: golang:1.14
    commands:
      - make ci-setup
      - make build-cross
    depends_on:
      - k3d_lint
      - k3d_tests
    when:
      branch:
        - master
      event:
        - push
        - tag

services:
  # Starting the docker service to be used by dind
  - name: docker
    image: docker:19.03-dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}