// createCluster creates a new cluster
func createCluster(ctx context.Context, cluster *types.Cluster) error {
    // ...
    for _, node := range cluster.Spec.Nodes {
        // ...
        node.NetworkMode = "host"
        // ...
    }
    // ...
    return cluster.Create(ctx)
}