// Node represents a k3d node
type Node struct {
    // ...
    NetworkMode string `json:"networkMode"`
    // ...
}

// NewNode returns a new node
func NewNode(name string, role NodeRole, image string, networkMode string) *Node {
    // ...
    node := &Node{
        // ...
        NetworkMode: networkMode,
        // ...
    }
    // ...
    return node
}