#!/bin/sh

# Run confd
confd -onetime -backend env

# Output Configuration
echo "===== Initial nginx configuration ====="
cat /etc/nginx/nginx.conf
echo "======================================="

# Start nginx
nginx -g 'daemon off;'