#!/bin/sh

# Run confd
set -e
confd -onetime -backend file -file /etc/confd/values.yaml -log-level debug
set +e

# Output Configuration
echo "===== Initial nginx configuration ====="
cat /etc/nginx/nginx.conf
echo "======================================="

# Start nginx
nginx -g 'daemon off;'