// CreateCluster creates a new cluster
func CreateCluster(ctx context.Context, cluster *Cluster) error {
    // ...
    for _, node := range cluster.Nodes {
        // ...
        containerConfig := &container.Config{
            // ...
            NetworkMode: container.NetworkMode(node.NetworkMode),
            // ...
        }
        // ...
    }
    // ...
    return nil
}