name: k3d.io

on:
  push:
    branches:
      - main
    tags:
      # only run on tags for real releases and special docs releases
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-docs.[0-9]+'
    # tags-ignore:
    #   - "*rc*"
    #   - "*beta*"
    #   - "*alpha*"
    #   - "*test*"
    #   - "*dev*"

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: python:3.9
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Requirements
        run: pip install -r docs/requirements.txt
      - name: Build with MkDocs (validation)
        run: |
          git config --global --add safe.directory /__w/k3d/k3d
          mkdocs build --verbose --clean --strict
          rm -r site/
      - name: Configure Git
        if: startsWith(github.ref, 'refs/tags/')
        id: git
        run: |
          git config --global user.name ghaction-k3d.io
          git config --global user.email ghaction@k3d.io
          echo tag=${GITHUB_REF#refs/tags/} >> $GITHUB_OUTPUT
      - name: Build & Deploy with Mike (versioned)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mike deploy --update-aliases --push --rebase ${{ steps.git.outputs.tag }} stable
      

